version: 2
jobs:
  build:
    docker:
      - image: markhibberd/haskell-circleci:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: 'refresh-static-and-libssl'
          command: 'apt-get -y update && apt-get -y upgrade && apt-get install -y libssl-dev'
      - restore_cache:
          keys:
            - 'mafia-cli-'
      - run:
          name: 'build'
          command: 'cabal update && ./mafia build -f static'
      - save_cache:
          key: 'mafia-cli-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'publish'
          command: './bin/publish'
